### ISSUE TITLE
broken pip installation - no supporting_languages.txt file

### ISSUE THREAD

**Issue by YontiLevin** [Kyubyong/word2word#1]
when installing using pip the supporting_languages.txt file was not downloaded.
had to create it by myself to make the package work

**Comment by Kyubyong** [comment]
So fast! We were working on it. Would you try again?

**Comment by YontiLevin** [comment]
🔥 🔥 🔥 
Fixed!!! 

thanks

**Comment by alphadl** [comment]
Same problem 10 min ago~ and now its okay... thx @Kyubyong
