### ISSUE TITLE
Python2 Support

### ISSUE THREAD

**Issue by loretoparisi** [Kyubyong/word2word#3]
For the ones that are still using Python2, I have prepared this version with small changes that enables Python2 support. The most important change is to support reading the Pickle `protocol=3` in Python2. Then it works like a charm.
https://github.com/loretoparisi/word2word

```sh
$ python
Python 2.7.16 (default, Mar  4 2019, 09:01:38) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from word2word import Word2word
>>> en2fr = Word2word("en", "fr")
>>> print(en2fr("apple"))
[u'pomme', u'pommes', u'pommier', u'tartes', u'fleurs']
```

**Comment by kimdwkimdw** [comment]
Python2 will retire soon. Only 2 months left.
https://pythonclock.org
