### ISSUE TITLE
Complete installation is not explained

### ISSUE THREAD

**Issue by BryanKoo** [Kyubyong/word2word#5]
This is interesting project but complete installation is not explained at all.

In README, the author says "Then, in Python, download the model and retrieve top-k word translations of any given word to the desired language."

Where can I find the way how to download model ?

**Comment by BryanKoo** [comment]
I tried to install further by running make.py.
I needed to install pyvi for en2vi installation.
But ended up with following messages.
What a waste of time~
Do not make open repository, if you do not want to share the code honestly !!

Traceback (most recent call last):
  File "make.py", line 275, in <module>
    main(hp)
  File "make.py", line 169, in main
    sents1 = refine(fin, lang1, hp.max_lines, tokenizer1, hp.ignore_first_word1)
  File "make.py", line 65, in refine
    sents = [normalize(word_segment(sent, lang, tokenizer), lang, ignore_first_word) for sent in tqdm(lines)]
  File "make.py", line 65, in <listcomp>
    sents = [normalize(word_segment(sent, lang, tokenizer), lang, ignore_first_word) for sent in tqdm(lines)]
TypeError: normalize() takes 2 positional arguments but 3 were given

**Comment by kimdwkimdw** [comment]
Checkout `Usage` https://github.com/Kyubyong/word2word#usage

Installation is totally simple. Just use pip. Don't you know Python standard pip?
```
pip install word2word
```

Moreover, if you just want to use `en2vi` model, try code in below.


```
from word2word import Word2word

en2vi = Word2word("en", "vi")
print(en2vi("apple"))
```

Don't be rude. I think you don't need `make.py` even though there is a bug.
