### ISSUE TITLE
query fails without an informative error message

### ISSUE THREAD

**Issue by rachel-sorek** [Kyubyong/word2word#7]
in some cases a query fails on:
ys = self.x2ys[x]
without an informative error message.

to reproduce:
en2fr = Word2word('en', 'fr') 
en2fr('00')

**Comment by yjchoe** [comment]
Hi @rachel-sorek,

Thanks for pointing this out. The updated version provides a (slightly) more informative message. 
https://github.com/Kyubyong/word2word/blob/master/word2word/word2word.py#L64

```
In [11]: en2fr('0000')
...
KeyError: 'query word 0000 not found in the bilingual lexicon.'
```

Hope this helps!
